/// <summary>6x11 pixel font (DejaVu Sans Mono 9 px, 1-bit) for the in-game terminal and ID card.</summary>
public static class PixelFont
{
    public const int CellWidth = 6;
    public const int CellHeight = 11;
    const string Chars = " !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~ÄÖÜäöüß°";
    const string Data = "AAAAAAAAAAAAAAAABAQEBAQABAAAAAAKCgAAAAAAAAAAAAwKHwofBgUAAAAACDwKDjgoHggAAAAHBRcMHhQcAAAAABwEBAwaChwAAAAABAQAAAAAAAAAAAgEBAQEBAQIAAAABAQICAgIBAQAAAAAFQ4OFQAAAAAAAAAAAAQEHwQEAAAAAAAAAAAAAAQEBAAAAAAAAAwAAAAAAAAAAAAAAAAEAAAAAAgEBAYCAgEAAAAADBISGhISDAAAAAAMCAgICAgcAAAAAAwSEBgMBh4AAAAADBIQDBAQDgAAAAAICAwMCh4IAAAAAB4CAg4QEA4AAAAAHAYCHhISDAAAAAAeEAgICAwEAAAAAAwSEgwSEgwAAAAADBISHhAYDgAAAAAAAAQAAAAEAAAAAAAABAAAAAQEBAAAAAAgHA4wAAAAAAAAAAAfAB8AAAAAAAAAAhw4BgAAAAAAHhAIBAQABAAAAAAADBIaGhoGDAAAAAwMDBISHhIAAAAADhISDhISHgAAAAAcAgICAgIcAAAAAA4SEhISEg4AAAAAHgICHgICHgAAAAAeAgIeAgICAAAAABwCAhoSEhwAAAAAEhISHhISEgAAAAAOBAQEBAQOAAAAABwQEBAQEB4AAAAAEgoGBgoKEgAAAAACAgICAgIeAAAAABIeHh4eEhIAAAAAEhYWGhoaEgAAAAAMEhISEhIMAAAAAA4SEg4CAgIAAAAADBISEhISDBAAAAAOEhIOGhIiAAAAAAwSAhwQEgwAAAAAHwQEBAQEBAAAAAASEhISEhIMAAAAABISDAwMDAwAAAAAEREVGwoKCgAAAAASEgwMDBISAAAAABEKCgQEBAQAAAAAHhAICAQCHgAAAAwEBAQEBAQMAAAAAAECAgYEBAgAAAAMCAgICAgIDAAAAAAECwAAAAAAAAAAAAAAAAAAAAAAHwACBAAAAAAAAAAAAAAAAA4QHhIeAAAAAgICDhISEg4AAAAAAAAcAgICHAAAABAQEBwSEhIcAAAAAAAADBIeAhwAAAAYBAQeBAQEBAAAAAAAABwSEhIcEAwAAgICHhISEhIAAAAEAAAGBAQEHwAAAAgAAAwICAgICA4AAgICEgoGChIAAAAHBAQEBAQEGAAAAAAAAD4qKioqAAAAAAAAHhISEhIAAAAAAAAMEhISDAAAAAAAAA4SEhIOAgIAAAAAHBISEhwQEAAAAAAcBAQEBAAAAAAAAB4CHBAeAAAAAAAEHgQEBBwAAAAAAAASEhISHgAAAAAAABISDAwMAAAAAAAAERUKCgoAAAAAAAASDAwMEgAAAAAAABISDAwEBAYAAAAAHggMBB4AAAAMBAQCBAQEDAAAAAQEBAQEBAQEBAAABgQECAQEBAYAAAAAAAAADjAAAAAAAAAMDAwSEh4SAAAAAAwSEhISEgwAAAAAEhISEhISDAAAAAAKAA4QHhIeAAAAABIADBISEgwAAAAAEgASEhISHgAAAA4KDgYGGhIaAAAAAA4KDgAAAAAAAAA=";

    static byte[] glyphs;

    /// <summary>Bits of one glyph row (bit 0 = leftmost pixel). Unknown characters show as '?'.</summary>
    public static int Row(char c, int row)
    {
        if (glyphs == null) glyphs = System.Convert.FromBase64String(Data);
        int i = Chars.IndexOf(c);
        if (i < 0) i = Chars.IndexOf('?');
        return glyphs[i * CellHeight + row];
    }
}
